### ISSUE TITLE
Tài liệu hướng dẫn - Manual

### ISSUE THREAD

**Issue by nnthuan** [nnthuan/IoTIDE#35]
Thảo luận các vấn đề về tài liệu hướng dẫn sử dụng - Manual.

**Comment by HuuThuat1996** [comment]
![screencapture-file-c-users-dell-desktop-test_iot-test_iot-html-1520323344346](https://user-images.githubusercontent.com/24569996/37020736-77df1f16-214f-11e8-9739-4c543f44fcf5.png)
giao diện manual

**Comment by nnthuan** [comment]
Nhìn nó mất cân xứng. Với lại cho xem tài liệu khi chuyển sang  pdf.

**Comment by HuuThuat1996** [comment]
![screencapture-file-c-users-dell-desktop-kkkk_iot-html-2018-03-15-11_53_23](https://user-images.githubusercontent.com/24569996/37444984-82f65b4a-2847-11e8-99cf-657186ab91a1.png)

**Comment by nnthuan** [comment]
Line nhỏ lại chút nữa.
Chiều rộng các cột cần phải điều chỉnh lại cho phù hợp hơn.
Thường thì hay lắp rắp theo hướng như sau: Đâu tiên LED thì gắn vào chân của mainboard nào, keypad thì gắn vào chân của mainboard -> cột đâu tiên nên là TypeOfcontrol và phải là một dãy liên tục của control đó, tiếp là PinOfControl, Tiếp nữa là PinOf<Tên của mainboard luông>.

**Comment by HuuThuat1996** [comment]
do nheiu62 hàng nên để khoảng cách thế dễ nhìn.
![screencapture-file-c-users-dell-desktop-saa_iot-html-2018-03-15-13_36_39](https://user-images.githubusercontent.com/24569996/37447756-0aa1c62a-2856-11e8-8080-13f487041a60.png)

**Comment by nnthuan** [comment]
Nếu cột 1 nhỏ, cột 2 nhỏ và cột 3 là phần còn lại thì thế nào?
và còn vấn đề là sắp xếp các control thì sao

**Comment by HuuThuat1996** [comment]
![image](https://user-images.githubusercontent.com/24569996/37448179-d1c4c7d8-2857-11e8-8e92-ceb62900f488.png)

**Comment by HuuThuat1996** [comment]
nếu cho các control ra cột 1 thì nó như thế này: giống như có 2 cách diễn đạt 1 : những pin của mainboard kết nối với nhưng thiết bị nào.
2 là Những thiết bị kết nối với mainboard như thế nào.
Chọn cách nào thấy hợp lý trong trường hợp này thì chọn

**Comment by nnthuan** [comment]
cái hình mới gửi được hơn. Như mà làm sao merger cái keypad 4x4 vào thành một thì sẽ gọn hơn

**Comment by nnthuan** [comment]
Mẫu bảng như thế này 
![Chiều rộng cột như thế này](https://user-images.githubusercontent.com/23269534/37448628-b9a85816-2859-11e8-9b9f-7df4056a117f.png)

**Comment by HuuThuat1996** [comment]
j thế
![screencapture-file-c-users-dell-desktop-lll_iot-html-2018-03-15-14_16_20](https://user-images.githubusercontent.com/24569996/37449067-81193b58-285b-11e8-8377-d21cc23c7be3.png)

**Comment by HuuThuat1996** [comment]
nếu in ra pdf thì thế này
[p.pdf](https://github.com/nnthuan/IoTIDE/files/1814317/p.pdf)

**Comment by tonlongphuoc** [comment]
@nnthuan:
Giao diện cũng đơn giản hơn rồi, tuy nhiên mình sẽ điều chỉnh một số như:

Lỗi chính tả: List Control phải sửa lại List of Controls, tương tự mình xem lại số nhiều các tiêu đề nhé.
Bố cục của manual là được nhưng chưa thật sự phù hợp lắm như:
 - phải có tên projects.
 -ngày tạo
-...
Thuật xem lại và hiệu chỉnh cho hợp lý hơn nhé.

**Comment by HuuThuat1996** [comment]
![screencapture-file-c-users-dell-desktop-p_cafeteria-html-2018-03-15-16_43_19](https://user-images.githubusercontent.com/24569996/37455591-00fbec3a-2870-11e8-970d-ac243e2602ca.png)

**Comment by HuuThuat1996** [comment]
![screencapture-file-c-users-dell-desktop-test_cafeteria-html-2018-03-15-16_50_19](https://user-images.githubusercontent.com/24569996/37456103-356fdc64-2871-11e8-872e-7000163cc976.png)

**Comment by nnthuan** [comment]
Nên để thông tin ngay dưới tiêu đề luôn.
